# Generated by Django 2.2.2 on 2019-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0002_auto_20190623_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_id',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
