# Generated by Django 2.2.2 on 2019-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0006_auto_20190630_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
